### PR TITLE
removed Txar and Altair

### PR DESCRIPTION
**Pull request by Floofball-uwu**
they are no more and didnt contribute to the final music (i gotta update the music in this repo at some point)

### CODE REVIEW

**Comment by Txar** [comment]
yesss I approve I told python to do this but he literally just said no

**Comment by ThePythonGuy3** [comment]
sigh fine

**Comment by Janssendel** [comment]
soch

**Comment by Janssendel** [comment]
actually i havent seen abything for a quite long period of time so that's why i was inactive

**Pull request merged**
